I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 644, in script
    jump invitationRefuse2
ScriptError: could not find label 'invitationRefuse2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 644, in script
    jump invitationRefuse2
  File "C:\Users\yamin\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 1699, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\yamin\Downloads\renpy-8.3.2-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'invitationRefuse2'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.2.24090902
Cybergarde part two 1.0
Tue Apr  1 10:41:58 2025
